# Generated by Django 2.2.10 on 2020-09-12 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('part4', '0002_auto_20200911_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('contact', models.CharField(max_length=12)),
                ('address', models.CharField(max_length=300)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.DeleteModel(
            name='Register',
        ),
    ]
