# Generated by Django 2.2.10 on 2020-09-15 07:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parteight', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employee data',
        ),
    ]
