# Generated by Django 2.2.10 on 2020-09-15 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parteight', '0002_auto_20200915_1321'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employee',
            table='employees data',
        ),
    ]
